### ISSUE TITLE
大牛对nixos下打包dingding有兴趣吗？

### ISSUE THREAD

**Issue by SadSock** [LostAttractor/flake#1]
您好，我看您打包了QQ，我想打包个dingding但是不知道从哪里入手。大牛对打包钉钉有兴趣吗？

QQ和钉钉都是electron实现的，两者的打包方法应该差不多。

我想打包个钉钉，我该从哪里入手？

**Comment by LostAttractor** [comment]
nur里有人打包，你可以试试看
https://github.com/nix-community/nur-combined/blob/master/repos/xddxdd/pkgs/uncategorized/dingtalk/default.nix
如果有空我梳理一下打一个发pr到nixpkgs
还有就是，善用nur，很多人为了省事是打完包往自己nur里一放就懒得管了，没时间发pr的。。

**Comment by SadSock** [comment]
谢谢 大佬 我试试看

**Comment by SadSock** [comment]
打包的教程我该去哪里找，nixos的文档，对新手很不友好

**Comment by SadSock** [comment]
我配置好了nur的源以后，我不知道dingtalk这个包的名字，怎么办？

nix-env -iA dingtalk

提示找不到这个package
